In [723]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [724]:
df = pd.read_csv('/content/customer (2).csv')[['review','education','purchased']]

In [725]:
df.shape


(50, 3)

In [726]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [727]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     50 non-null     object
 1   education  50 non-null     object
 2   purchased  50 non-null     object
dtypes: object(3)
memory usage: 1.3+ KB


In [728]:
x = df.drop('purchased',axis=1)
y = df['purchased']

In [729]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [730]:
x_train.shape,x_test.shape

((40, 2), (10, 2))

In [731]:
from sklearn.preprocessing import OrdinalEncoder

In [732]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [733]:
oe.categories

[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']]

In [734]:
x_train = oe.fit_transform(x_train)
x_test = oe.transform(x_test)

In [735]:
from sklearn.preprocessing import LabelEncoder

In [736]:
le = LabelEncoder()

In [749]:
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [751]:
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [753]:
from sklearn.linear_model import LogisticRegression

In [754]:
lr = LogisticRegression()

lr.fit(x_train,y_train)

LogisticRegression()

In [755]:
lr.coef_

array([[0.05280352, 0.32913653]])

In [756]:
lr.intercept_

array([-0.10295313])

In [757]:
y_pred = lr.predict(x_test)

In [758]:
y_pred

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 1])

In [759]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [760]:
print(accuracy_score(y_pred,y_test)*100)
print(confusion_matrix(y_pred,y_test))
print(classification_report(y_pred,y_test))


50.0
[[3 3]
 [2 2]]
              precision    recall  f1-score   support

           0       0.60      0.50      0.55         6
           1       0.40      0.50      0.44         4

    accuracy                           0.50        10
   macro avg       0.50      0.50      0.49        10
weighted avg       0.52      0.50      0.51        10



In [748]:
import pickle

In [761]:
pickle.dump(lr,open('Ordinal_Encoding.pk','wb'))