In [144]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [145]:
df = pd.read_csv('/content/Social_Network_Ads.csv')[['Age','EstimatedSalary','Purchased']]

In [146]:
df.shape


(400, 3)

In [147]:
df.sample(5)

Age  EstimatedSalary  Purchased
262   55           125000          1
89    35            50000          0
113   37            55000          0
64    59            83000          0
150   26            15000          0

In [148]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB


In [149]:
x = df.drop('Purchased',axis=1)
y = df['Purchased']

In [150]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [151]:
x_train

Age  EstimatedSalary
205   47            47000
354   36            99000
3     27            57000
264   48            90000
194   28            89000
..   ...              ...
299   46           117000
22    48            41000
72    20            23000
15    29            80000
168   29           148000

[320 rows x 2 columns]

In [152]:
x_train.shape,x_test.shape

((320, 2), (80, 2))

In [153]:
from sklearn.preprocessing import StandardScaler

In [154]:
scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [156]:
x_train_scaled = pd.DataFrame(x_train_scaled,columns=x_train.columns)
x_test_scaled = pd.DataFrame(x_test_scaled,columns=x_test.columns)

In [169]:
np.round(x_train_scaled.describe(),1)

Age  EstimatedSalary
count  320.0            320.0
mean    -0.0             -0.0
std      1.0              1.0
min     -1.9             -1.6
25%     -0.8             -0.8
50%     -0.1              0.0
75%      0.8              0.5
max      2.1              2.4

In [158]:
from sklearn.linear_model import LogisticRegression

In [159]:
lr = LogisticRegression()

lr.fit(x_train_scaled,y_train)

LogisticRegression()

In [160]:
lr.coef_

array([[2.22371989, 1.17221606]])

In [161]:
lr.intercept_

array([-1.19266667])

In [162]:
y_pred = lr.predict(x_test_scaled)

In [163]:
y_pred

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0])

In [164]:
y_test.values

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0])

In [165]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [166]:
print(accuracy_score(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))
print(classification_report(y_pred,y_test))


0.8125
[[45 12]
 [ 3 20]]
              precision    recall  f1-score   support

           0       0.94      0.79      0.86        57
           1       0.62      0.87      0.73        23

    accuracy                           0.81        80
   macro avg       0.78      0.83      0.79        80
weighted avg       0.85      0.81      0.82        80

